### PR TITLE
Delete unused DataTask

### PR DESCRIPTION
**Pull request by JonChesterfield**
Dead code.

### CODE REVIEW

**Comment by estewart08** [comment]
Pulled in the patch, rebuilt openmp, no unexpected errors with gfx906 testing.

**Comment by JonChesterfield** [comment]
Thanks!

**Comment by ashwinma** [comment]
Just FYI -- in case you want to add async data movement, you may want to revisit data tasks. I understand from a upstream point of view, it is a tad excessive at this point.

**Comment by JonChesterfield** [comment]
Hey Ashwin. Yeah, there's a bunch of interesting runtime things that could be done here.

Optimising for upstream or the unified compiler in the near future means staying with the libomptarget plugin, which doesn't have the hooks to offload much to atmi. 

Lots of the local copy of atmi is unused as a result, my plan is to delete all the bits that aren't in use to unblock reviews.

**Comment by ashwinma** [comment]
Yep, makes perfect sense to me.

**Pull request merged**
