### PR TITLE
Rename plugin/hsa to plugin/amdgpu

### PR DESCRIPTION
**Pull request by JonChesterfield**
Leaving file updates to a second patch, in order to maximise the number of files marked 'File renamed without changes.'

### CODE REVIEW

**Review by ronlieb — APPROVED** [review]
perhaps ethan could try the patch before landing it?

**Comment by JonChesterfield** [comment]
Sure, it builds and runs fine for me (on the second try, forgot about the array of strings in src/rtl.cpp on the first run)

**Comment by estewart08** [comment]
**Build failure during openmp:**
```amd-llvm-project/openmp/libomptarget/hostrpc/services/hostrpc_internal.h:208:10: fatal error: ../../plugins/hsa/impl/atmi_runtime.h: No such file or directory```
 ```#include "../../plugins/hsa/impl/atmi_runtime.h"```

This include needs **hsa** switched to **amdgpu.**

Smoke tests showed failure to offload to gpu and fallback to host. The libomptarget.rtl.hsa.so was not being picked up. Changing the name to libomptarget.rtl.amdgpu.so worked. Additional changes to ```amd-llvm-project/openmp/libomptarget/plugins/amdgpu/CMakeLists.txt``` are needed to convert name omptarget.rtl.hsa to omptarget.rtl.amdgpu.

**Comment by JonChesterfield** [comment]
Thanks for the note. Abandoning this because the branches are being moved around, will try again some time later.

**Comment by JonChesterfield** [comment]
needs code changes, and the change-base doesn't appear to facilitate that. abandoning

**Pull request closed without merging**
