### PR TITLE
Update shared variable linkage, without breaking gfx803

### PR DESCRIPTION
**Pull request by JonChesterfield**
Reimplement pull/196, excluding the parts that break on gfx803. Left comments inline to that effect.

### CODE REVIEW

**Review by ronlieb — COMMENTED** [review]
not clear to me, what did you have to do for this patch to work with gfx803 ?

**Comment by JonChesterfield** [comment]
It does work for gfx803. At least, if I build it on r3, it passes the tests I expect it to.

**Review by ronlieb — COMMENTED** [review]
i assumed it was working, i was wondering what needed to change and perhaps why gfx803 was not working before?

**Comment by JonChesterfield** [comment]
Unclear - the private/internal linkage should make no difference, and the address space qualifier should make no difference either.

The bug could be in the loader, back end, hardware. Given no debugger and a symptom of 'invalid address' on code that works on later ISA's it's hard to pin down what the problem is.

**Review by ronlieb — APPROVED** [review]

**Pull request merged**
