### PR TITLE
Drop two passes that are not in upstream

### PR DESCRIPTION
**Pull request by JonChesterfield**
Either upstream. Some context in https://reviews.llvm.org/D69679

### CODE REVIEW

**Comment by JonChesterfield** [comment]
Which post commit testing? These passes are gone from llvm trunk and from amd-stg-open.

**Comment by ronlieb** [comment]
our post commit testing, where after you merged, which is now complete, I do a full build and test, its all manual.    although manual is just 3 commands   
./clone_aomp.sh
./build_aomp.sh
~/bin/runalltests

**Comment by JonChesterfield** [comment]
What's in your runalltests?

**Comment by ronlieb** [comment]
#!/bin/bash
set -x
export AOMP=~/rocm/aomp_11.5-0
export TDIR=~/git/aomp11/aomp
export MPI=/opt/openmpi-4.0.2/

cd $TDIR/test/smoke
./check_smoke.sh > /tmp/tlog1 2>&1
cd $TDIR/test/hip-openmp
./check_hip-openmp.sh > /tmp/tlog2 2>&1
cd $TDIR/test//omp5
./check_omp5.sh > /tmp/tlog3 2>&1
cd $TDIR/examples
./check_examples.sh > /tmp/tlog4 2>&1
cd $TDIR/bin
./run_nekbone.sh > /tmp/tlog5 2>&1
./run_sollve.sh > /tmp/tlog6 2>&1
cd ~/git/aomp-test/openmpapps
LD_LIBRARY_PATH=$MPI/lib/:$LD_LIBRARY_PATH  OMPIDIR=$MPI ./check_openmpapps.sh > /tmp/tlog7 2>&1

cd /work/rlieberm/SPEC/acc_1.3v3
set +x
. ./shrc
set -x
(ulimit -s unlimited; LIBRARY_PATH=$AOMP/lib LD_LIBRARY_PATH=$AOMP/lib:$LD_LIBRARY_PATH PATH=$AOMP/bin:$PATH runspec -c amd_omp.cfg -I -l -n 1 -T base,peak -i test openmp --rebuild ) 2>&1 | tee /tmp/tlog8

cd /work/rlieberm/SPEC/hpc2020-020
set +x
. ./shrc
set -x
LIBRARY_PATH=$AOMP/lib OMPI_FC=flang OMPI_CC=clang OMPI_CXX=clang++ LD_LIBRARY_PATH=$AOMP/lib:$MPI/lib/ PATH=$AOMP/bin:$MPI/bin:$PATH runhpc -c amdgpu_clang.cfg -I -l -n 1 -T base --define acctype=mpi --threads=1 --ranks=32 -i test speedlibs speedsmall --rebuild 2>&1 | tee /tmp/tlog9
LIBRARY_PATH=$AOMP/lib OMPI_FC=flang OMPI_CC=clang OMPI_CXX=clang++ LD_LIBRARY_PATH=$AOMP/lib:$MPI/lib/ PATH=$AOMP/bin:$MPI/bin:$PATH runhpc -c amdgpu_clang.cfg -I -l -n 1 -T base --define acctype=omp --threads=32 --ranks=1  -i test speedlibs speedsmall --rebuild 2>&1 | tee /tmp/tlog10
LIBRARY_PATH=$AOMP/lib OMPI_FC=flang OMPI_CC=clang OMPI_CXX=clang++ LD_LIBRARY_PATH=$AOMP/lib:$MPI/lib/ PATH=$AOMP/bin:$MPI/bin:$PATH runhpc -c amdgpu_clang.cfg -I -l -n 1 -T base --define acctype=omp_target --threads=1 --ranks=1  -i test speedlibs speedsmall --rebuild 2>&1 | tee /tmp/tlog11

**Comment by ronlieb** [comment]
bit of an eye chart

**Comment by ronlieb** [comment]
I believe one of these two passes, possibly both are still needed, probably both, because they are both present in amd-stg-open branch, and were never upstreamed, as near as I can tell.

**Comment by JonChesterfield** [comment]
That's unfortunate. I also see them in the amd-stg-open branch, must have misread the diff.

**Pull request merged**
