### PR TITLE
support for a hostrpc service to call a host function with a function…

### PR DESCRIPTION
**Pull request by gregrodgers**
… pointer with no arguments.  hostrpc_fptr0() .  The demo of this is in examples/openmp/host_function.

### CODE REVIEW

**Comment by JonChesterfield** [comment]
I think I'd expect this to call the host function once per active warp. Is that the case?

**Comment by ronlieb** [comment]
[AMD Official Use Only - Internal Distribution Only]

Hmm, the test case looks like it does it once per thread ?

**Comment by gregrodgers** [comment]
It acts as if it is once per thread.  However, the internals do an aggregate rpc call once per warp.   To get it to appear to run once per warp you would have to put a mask on with an if statement.   On Friday, Ron and I talked about getting hostrpc_fptr0(fptr) to return an int but then that would require the function that the function pointer represents to always return an int so we are leaving this as is.  I am working on more powerful hostrpc_varfn(...) which would take a host function pointer but with a variable number of args.

**Comment by gregrodgers** [comment]
Ron, please approve and merge this so we can continue cleanup effort on hostrpc and hsa/impl.

**Comment by ronlieb** [comment]
[AMD Official Use Only - Internal Distribution Only]

I approved it 3 days ago, merged in now.

**Pull request merged**
